baseurl = "https://jbfreels.com/unicorn-name/"
title = "What is your unicorn name?"
theme = "nix"
languageCode = "en-us"

[menu]

[params]
  custom_js = ['js/unicorn.js']
  GithubID = "jbfreels"
  TwitterID = "jbfreels"
  FacebookID = "jbfreels"
  Name = "Unicorn Name"
  HeaderUsername = "unicorn-name"
  HeaderHostname = "jbfreels.com"
  Email = "jbfreels@me.com"
  About = "enter your name and hit 'Submit'"
  ProfilePicture = "images/unicorn.jpg"
  Screenshot = "https://www.jbfreels.com/unicorn-name/images/screenshot.png"
  Copyright = "jbfreels"
